# Generated by Django 4.1.3 on 2022-11-25 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=200, verbose_name='Product Name')),
                ('prod_date', models.DateTimeField(default=datetime.datetime(2022, 11, 25, 10, 44, 28, 130209, tzinfo=datetime.timezone.utc), verbose_name='Product Date')),
                ('prod_description', models.TextField(verbose_name='Product Description')),
                ('prod_price', models.IntegerField(max_length=6, verbose_name='Product Price')),
                ('category', models.CharField(choices=[('Building Supplies', 'Bsu'), ('Tools', 'Tls'), ('Electrics', 'Elc'), ('Engineer Systems', 'Ens')], default='Building Supplies', max_length=19)),
            ],
        ),
    ]
