# Generated by Django 4.1.3 on 2022-11-25 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_product_category_product_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 25, 17, 58, 56, 452087, tzinfo=datetime.timezone.utc), verbose_name='Product Date'),
        ),
    ]
