# Generated by Django 4.1.3 on 2022-11-25 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_prod_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 25, 18, 11, 45, 662859, tzinfo=datetime.timezone.utc), verbose_name='Product Date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_description',
            field=models.TextField(max_length=2000, verbose_name='Product Description'),
        ),
    ]
