# Generated by Django 4.1.3 on 2022-11-25 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_product_prod_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 25, 19, 6, 11, 369048, tzinfo=datetime.timezone.utc), verbose_name='Product Date'),
        ),
    ]
