# Generated by Django 4.1.3 on 2022-12-07 02:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_product_prod_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Building Supplies', 'Bsu'), ('Tools', 'Tls'), ('Electrics', 'Elc'), ('Engineering Systems', 'Ens')], default='Building Supplies', max_length=19),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 2, 57, 25, 223882, tzinfo=datetime.timezone.utc), verbose_name='Product Date'),
        ),
    ]
