# Generated by Django 4.1.3 on 2022-12-14 05:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_product_image_alter_product_prod_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='prod_image',
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 5, 19, 4, 323270, tzinfo=datetime.timezone.utc), verbose_name='Product Date'),
        ),
    ]
