# Generated by Django 4.1.3 on 2022-12-14 05:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_image_product_prod_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 5, 20, 45, 544434, tzinfo=datetime.timezone.utc), verbose_name='Product Date'),
        ),
    ]
