# Generated by Django 4.1.3 on 2022-12-15 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_product_prod_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 15, 9, 40, 48, 25818, tzinfo=datetime.timezone.utc), verbose_name='Product Date'),
        ),
    ]
